---
- hosts: all
  become: yes
  tasks:
  - name: i want to intall git,tree,wget by using same tasks
    apt:
      name: "{{ item }}"
      state: present
    loop:
      - git
      - tree
      - wget